<?php

namespace Database\Seeders;

use App\Models\Room;
use Illuminate\Database\Seeder;
use Illuminate\Support\Str;

class RoomSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $rooms = [
            [
                'title' => 'Deluxe Room',
                'slug' => 'deluxe-room',
                'description' => '<h2>Spacious and Comfortable</h2><p>Our <strong>Deluxe Room</strong> offers a perfect blend of comfort and elegance. Featuring modern amenities and elegant decor, this room is ideal for couples and families seeking a comfortable stay.</p><ul><li>King Size Bed</li><li>City View</li><li>Modern Bathroom</li></ul>',
                'price' => 3500.00,
                'discount_price' => 3000.00,
                'type' => 'Deluxe',
                'available_rooms' => 5,
                'facilities' => ['Free Wi-Fi', '32" LED TV with satellite channels', 'AC', 'Mini Bar', 'Room Service'],
                'edit_message' => '<p><strong>Special Offer:</strong> Book now and get <em>15% discount</em> on your stay!</p>',
                'is_active' => true,
                'order' => 1,
            ],
            [
                'title' => 'Super Deluxe Room',
                'slug' => 'super-deluxe-room',
                'description' => '<h2>Enhanced Luxury</h2><p>Experience enhanced luxury with our <strong>Super Deluxe Room</strong>. This spacious room features premium furnishings and additional space for ultimate comfort during your stay.</p><ul><li>King Size Bed with Premium Linens</li><li>Balcony with Garden View</li><li>Luxury Bathroom with Bathtub</li></ul>',
                'price' => 5000.00,
                'discount_price' => 4500.00,
                'type' => 'Super Deluxe',
                'available_rooms' => 3,
                'facilities' => ['Free Wi-Fi', '43" Smart TV', 'AC', 'Mini Bar', 'Room Service', 'Balcony', 'Work Desk'],
                'edit_message' => '<p><strong>Premium Experience:</strong> Enjoy <em>complimentary breakfast</em> and <em>late checkout</em> with this room!</p>',
                'is_active' => true,
                'order' => 2,
            ],
            [
                'title' => 'Suite Room',
                'slug' => 'suite-room',
                'description' => '<h2>Our Finest Accommodation</h2><p>Our <strong>Suite Room</strong> is our finest accommodation featuring a separate living area and royal amenities. Perfect for business travelers and families who need extra space.</p><ul><li>Separate Living Area</li><li>Master Bedroom</li><li>Premium Bathroom with Jacuzzi</li><li>Private Balcony</li></ul>',
                'price' => 8500.00,
                'discount_price' => 7500.00,
                'type' => 'Suite',
                'available_rooms' => 2,
                'facilities' => ['Free Wi-Fi', '55" Smart TV', 'AC', 'Mini Bar', 'Room Service', 'Private Balcony', 'Work Desk', 'Dining Area', 'Jacuzzi'],
                'edit_message' => '<p><strong>Royal Treatment:</strong> Includes <em>butler service</em>, <em>complimentary spa access</em>, and <em>airport transfers</em>!</p>',
                'is_active' => true,
                'order' => 3,
            ],
            [
                'title' => 'Executive Room',
                'slug' => 'executive-room',
                'description' => '<h2>Business-Class Comfort</h2><p>Designed for corporate travelers, our <strong>Executive Room</strong> features a dedicated work desk, high-speed internet, and all amenities needed for a productive stay.</p><ul><li>Queen Size Bed</li><li>Work Desk with Ergonomic Chair</li><li>High-Speed Internet</li></ul>',
                'price' => 4500.00,
                'discount_price' => null,
                'type' => 'Executive',
                'available_rooms' => 4,
                'facilities' => ['Free Wi-Fi', '40" Smart TV', 'AC', 'Mini Bar', 'Room Service', 'Work Desk', 'Printer Access'],
                'edit_message' => '<p><strong>Business Package:</strong> Includes <em>complimentary business center access</em> and <em>meeting room discounts</em>!</p>',
                'is_active' => true,
                'order' => 4,
            ],
            [
                'title' => 'Family Room',
                'slug' => 'family-room',
                'description' => '<h2>Perfect for Families</h2><p>Our <strong>Family Room</strong> is spacious and designed to accommodate families comfortably. Features multiple beds and family-friendly amenities.</p><ul><li>Two Queen Beds</li><li>Extra Bed Available</li><li>Family Bathroom</li></ul>',
                'price' => 6000.00,
                'discount_price' => 5500.00,
                'type' => 'Family',
                'available_rooms' => 3,
                'facilities' => ['Free Wi-Fi', '43" Smart TV', 'AC', 'Mini Bar', 'Room Service', 'Extra Bed', 'Kids Amenities'],
                'edit_message' => '<p><strong>Family Special:</strong> Kids stay <em>free</em> and enjoy <em>complimentary breakfast</em>!</p>',
                'is_active' => true,
                'order' => 5,
            ],
            [
                'title' => 'Standard Room',
                'slug' => 'standard-room',
                'description' => '<h2>Comfortable and Affordable</h2><p>Our <strong>Standard Room</strong> provides all essential amenities for a comfortable stay at an affordable price.</p><ul><li>Queen Size Bed</li><li>City View</li><li>Modern Bathroom</li></ul>',
                'price' => 2500.00,
                'discount_price' => 2200.00,
                'type' => 'Standard',
                'available_rooms' => 8,
                'facilities' => ['Free Wi-Fi', '32" LED TV', 'AC', 'Room Service'],
                'edit_message' => '<p><strong>Budget Friendly:</strong> Perfect for <em>budget-conscious travelers</em>!</p>',
                'is_active' => true,
                'order' => 6,
            ],
            [
                'title' => 'Premium Room',
                'slug' => 'premium-room',
                'description' => '<h2>Premium Comfort</h2><p>Our <strong>Premium Room</strong> offers enhanced comfort with premium amenities and elegant decor.</p><ul><li>King Size Bed</li><li>Garden View</li><li>Luxury Bathroom</li></ul>',
                'price' => 4000.00,
                'discount_price' => 3600.00,
                'type' => 'Premium',
                'available_rooms' => 6,
                'facilities' => ['Free Wi-Fi', '40" Smart TV', 'AC', 'Mini Bar', 'Room Service', 'Balcony'],
                'edit_message' => '<p><strong>Premium Offer:</strong> Get <em>10% discount</em> on extended stays!</p>',
                'is_active' => true,
                'order' => 7,
            ],
            [
                'title' => 'Luxury Suite',
                'slug' => 'luxury-suite',
                'description' => '<h2>Ultimate Luxury</h2><p>Our <strong>Luxury Suite</strong> provides the ultimate in comfort and luxury with premium furnishings and exclusive amenities.</p><ul><li>King Size Bed</li><li>Separate Living Area</li><li>Premium Bathroom</li><li>Private Balcony</li></ul>',
                'price' => 10000.00,
                'discount_price' => 9000.00,
                'type' => 'Luxury Suite',
                'available_rooms' => 2,
                'facilities' => ['Free Wi-Fi', '65" Smart TV', 'AC', 'Mini Bar', 'Room Service', 'Private Balcony', 'Jacuzzi', 'Butler Service'],
                'edit_message' => '<p><strong>Luxury Package:</strong> Includes <em>complimentary spa</em>, <em>airport transfers</em>, and <em>dining credits</em>!</p>',
                'is_active' => true,
                'order' => 8,
            ],
            [
                'title' => 'Business Room',
                'slug' => 'business-room',
                'description' => '<h2>Perfect for Business</h2><p>Our <strong>Business Room</strong> is designed for corporate travelers with dedicated workspace and business amenities.</p><ul><li>Queen Size Bed</li><li>Work Desk</li><li>High-Speed Internet</li></ul>',
                'price' => 3800.00,
                'discount_price' => 3500.00,
                'type' => 'Business',
                'available_rooms' => 5,
                'facilities' => ['Free Wi-Fi', '40" Smart TV', 'AC', 'Work Desk', 'Printer Access', 'Room Service'],
                'edit_message' => '<p><strong>Business Special:</strong> <em>Complimentary breakfast</em> and <em>late checkout</em>!</p>',
                'is_active' => true,
                'order' => 9,
            ],
            [
                'title' => 'Honeymoon Suite',
                'slug' => 'honeymoon-suite',
                'description' => '<h2>Romantic Getaway</h2><p>Our <strong>Honeymoon Suite</strong> is perfect for couples celebrating their special moments with romantic decor and special amenities.</p><ul><li>King Size Bed</li><li>Romantic Decor</li><li>Premium Bathroom</li><li>Private Balcony</li></ul>',
                'price' => 7500.00,
                'discount_price' => 6800.00,
                'type' => 'Honeymoon Suite',
                'available_rooms' => 2,
                'facilities' => ['Free Wi-Fi', '50" Smart TV', 'AC', 'Mini Bar', 'Room Service', 'Private Balcony', 'Romantic Decor', 'Champagne Service'],
                'edit_message' => '<p><strong>Romantic Package:</strong> Includes <em>complimentary champagne</em>, <em>rose petals</em>, and <em>romantic dinner</em>!</p>',
                'is_active' => true,
                'order' => 10,
            ],
            [
                'title' => 'Presidential Suite',
                'slug' => 'presidential-suite',
                'description' => '<h2>Presidential Luxury</h2><p>Our <strong>Presidential Suite</strong> is the epitome of luxury with spacious living areas and exclusive services.</p><ul><li>Master Bedroom</li><li>Separate Living Room</li><li>Dining Area</li><li>Premium Bathroom</li></ul>',
                'price' => 15000.00,
                'discount_price' => 13500.00,
                'type' => 'Presidential Suite',
                'available_rooms' => 1,
                'facilities' => ['Free Wi-Fi', '75" Smart TV', 'AC', 'Mini Bar', 'Room Service', 'Private Balcony', 'Jacuzzi', 'Butler Service', 'Private Chef'],
                'edit_message' => '<p><strong>Presidential Experience:</strong> Includes <em>private chef</em>, <em>butler service</em>, and <em>limousine transfers</em>!</p>',
                'is_active' => true,
                'order' => 11,
            ],
            [
                'title' => 'Garden View Room',
                'slug' => 'garden-view-room',
                'description' => '<h2>Serene Garden Views</h2><p>Our <strong>Garden View Room</strong> offers peaceful views of our beautiful gardens, perfect for relaxation.</p><ul><li>Queen Size Bed</li><li>Garden View</li><li>Modern Bathroom</li></ul>',
                'price' => 3200.00,
                'discount_price' => 2900.00,
                'type' => 'Garden View',
                'available_rooms' => 7,
                'facilities' => ['Free Wi-Fi', '40" Smart TV', 'AC', 'Room Service', 'Garden View'],
                'edit_message' => '<p><strong>Nature Lovers:</strong> Enjoy <em>peaceful garden views</em> and <em>fresh air</em>!</p>',
                'is_active' => true,
                'order' => 12,
            ],
            [
                'title' => 'Pool View Room',
                'slug' => 'pool-view-room',
                'description' => '<h2>Poolside Comfort</h2><p>Our <strong>Pool View Room</strong> offers stunning views of our swimming pool area, perfect for those who love to relax by the water.</p><ul><li>King Size Bed</li><li>Pool View</li><li>Modern Bathroom</li><li>Balcony</li></ul>',
                'price' => 4200.00,
                'discount_price' => 3800.00,
                'type' => 'Pool View',
                'available_rooms' => 4,
                'facilities' => ['Free Wi-Fi', '43" Smart TV', 'AC', 'Mini Bar', 'Room Service', 'Pool View', 'Balcony'],
                'edit_message' => '<p><strong>Pool Access:</strong> Enjoy <em>direct pool access</em> and <em>poolside service</em>!</p>',
                'is_active' => true,
                'order' => 13,
            ],
            [
                'title' => 'City View Room',
                'slug' => 'city-view-room',
                'description' => '<h2>Urban Elegance</h2><p>Our <strong>City View Room</strong> offers panoramic views of the city skyline, perfect for urban explorers.</p><ul><li>Queen Size Bed</li><li>City View</li><li>Modern Bathroom</li></ul>',
                'price' => 3300.00,
                'discount_price' => 3000.00,
                'type' => 'City View',
                'available_rooms' => 6,
                'facilities' => ['Free Wi-Fi', '40" Smart TV', 'AC', 'Room Service', 'City View'],
                'edit_message' => '<p><strong>City Explorer:</strong> Perfect for <em>urban adventures</em> and <em>city sightseeing</em>!</p>',
                'is_active' => true,
                'order' => 14,
            ],
            [
                'title' => 'Ocean View Room',
                'slug' => 'ocean-view-room',
                'description' => '<h2>Breathtaking Ocean Views</h2><p>Our <strong>Ocean View Room</strong> offers stunning views of the ocean, perfect for beach lovers.</p><ul><li>King Size Bed</li><li>Ocean View</li><li>Premium Bathroom</li><li>Private Balcony</li></ul>',
                'price' => 5500.00,
                'discount_price' => 5000.00,
                'type' => 'Ocean View',
                'available_rooms' => 3,
                'facilities' => ['Free Wi-Fi', '50" Smart TV', 'AC', 'Mini Bar', 'Room Service', 'Ocean View', 'Private Balcony'],
                'edit_message' => '<p><strong>Beach Paradise:</strong> Wake up to <em>stunning ocean views</em> every morning!</p>',
                'is_active' => true,
                'order' => 15,
            ],
            [
                'title' => 'Mountain View Room',
                'slug' => 'mountain-view-room',
                'description' => '<h2>Mountain Serenity</h2><p>Our <strong>Mountain View Room</strong> offers peaceful views of the mountains, perfect for nature enthusiasts.</p><ul><li>Queen Size Bed</li><li>Mountain View</li><li>Modern Bathroom</li></ul>',
                'price' => 3600.00,
                'discount_price' => 3300.00,
                'type' => 'Mountain View',
                'available_rooms' => 5,
                'facilities' => ['Free Wi-Fi', '40" Smart TV', 'AC', 'Room Service', 'Mountain View'],
                'edit_message' => '<p><strong>Nature Retreat:</strong> Experience <em>peaceful mountain views</em> and <em>fresh mountain air</em>!</p>',
                'is_active' => true,
                'order' => 16,
            ],
            [
                'title' => 'Studio Apartment',
                'slug' => 'studio-apartment',
                'description' => '<h2>Spacious Studio</h2><p>Our <strong>Studio Apartment</strong> offers a complete living space with kitchenette, perfect for extended stays.</p><ul><li>Queen Size Bed</li><li>Kitchenette</li><li>Living Area</li><li>Modern Bathroom</li></ul>',
                'price' => 4800.00,
                'discount_price' => 4400.00,
                'type' => 'Studio',
                'available_rooms' => 4,
                'facilities' => ['Free Wi-Fi', '43" Smart TV', 'AC', 'Kitchenette', 'Room Service', 'Living Area'],
                'edit_message' => '<p><strong>Extended Stay:</strong> Perfect for <em>long-term guests</em> with <em>kitchen facilities</em>!</p>',
                'is_active' => true,
                'order' => 17,
            ],
            [
                'title' => 'Penthouse Suite',
                'slug' => 'penthouse-suite',
                'description' => '<h2>Top Floor Luxury</h2><p>Our <strong>Penthouse Suite</strong> is located on the top floor with panoramic views and exclusive amenities.</p><ul><li>Master Bedroom</li><li>Separate Living Room</li><li>Premium Bathroom</li><li>Private Terrace</li></ul>',
                'price' => 12000.00,
                'discount_price' => 11000.00,
                'type' => 'Penthouse',
                'available_rooms' => 1,
                'facilities' => ['Free Wi-Fi', '70" Smart TV', 'AC', 'Mini Bar', 'Room Service', 'Private Terrace', 'Jacuzzi', 'Butler Service'],
                'edit_message' => '<p><strong>Penthouse Experience:</strong> Enjoy <em>exclusive top-floor luxury</em> with <em>panoramic views</em>!</p>',
                'is_active' => true,
                'order' => 18,
            ],
            [
                'title' => 'Accessible Room',
                'slug' => 'accessible-room',
                'description' => '<h2>Fully Accessible</h2><p>Our <strong>Accessible Room</strong> is designed for guests with mobility needs, featuring wheelchair accessibility and special amenities.</p><ul><li>Queen Size Bed</li><li>Wheelchair Accessible</li><li>Accessible Bathroom</li></ul>',
                'price' => 3000.00,
                'discount_price' => 2800.00,
                'type' => 'Accessible',
                'available_rooms' => 3,
                'facilities' => ['Free Wi-Fi', '40" Smart TV', 'AC', 'Room Service', 'Wheelchair Accessible', 'Accessible Bathroom'],
                'edit_message' => '<p><strong>Inclusive Design:</strong> Fully <em>wheelchair accessible</em> with <em>special amenities</em>!</p>',
                'is_active' => true,
                'order' => 19,
            ],
            [
                'title' => 'Pet-Friendly Room',
                'slug' => 'pet-friendly-room',
                'description' => '<h2>Pet-Friendly Accommodation</h2><p>Our <strong>Pet-Friendly Room</strong> welcomes your furry friends with special amenities and pet-friendly facilities.</p><ul><li>Queen Size Bed</li><li>Pet Bed</li><li>Modern Bathroom</li></ul>',
                'price' => 3400.00,
                'discount_price' => 3100.00,
                'type' => 'Pet-Friendly',
                'available_rooms' => 4,
                'facilities' => ['Free Wi-Fi', '40" Smart TV', 'AC', 'Room Service', 'Pet Bed', 'Pet Amenities'],
                'edit_message' => '<p><strong>Pet Welcome:</strong> Your <em>pets are welcome</em> with <em>special amenities</em>!</p>',
                'is_active' => true,
                'order' => 20,
            ],
            [
                'title' => 'Junior Suite',
                'slug' => 'junior-suite',
                'description' => '<h2>Spacious Junior Suite</h2><p>Our <strong>Junior Suite</strong> offers more space than a standard room with a separate sitting area.</p><ul><li>King Size Bed</li><li>Sitting Area</li><li>Premium Bathroom</li></ul>',
                'price' => 5200.00,
                'discount_price' => 4800.00,
                'type' => 'Junior Suite',
                'available_rooms' => 3,
                'facilities' => ['Free Wi-Fi', '50" Smart TV', 'AC', 'Mini Bar', 'Room Service', 'Sitting Area'],
                'edit_message' => '<p><strong>Extra Space:</strong> Enjoy <em>more room</em> with <em>separate sitting area</em>!</p>',
                'is_active' => true,
                'order' => 21,
            ],
            [
                'title' => 'Corner Room',
                'slug' => 'corner-room',
                'description' => '<h2>Corner Views</h2><p>Our <strong>Corner Room</strong> offers corner views with extra windows and natural light.</p><ul><li>Queen Size Bed</li><li>Corner Views</li><li>Extra Windows</li><li>Modern Bathroom</li></ul>',
                'price' => 3700.00,
                'discount_price' => 3400.00,
                'type' => 'Corner',
                'available_rooms' => 5,
                'facilities' => ['Free Wi-Fi', '40" Smart TV', 'AC', 'Room Service', 'Corner Views', 'Extra Windows'],
                'edit_message' => '<p><strong>Corner Advantage:</strong> Enjoy <em>extra windows</em> and <em>more natural light</em>!</p>',
                'is_active' => true,
                'order' => 22,
            ],
            [
                'title' => 'Twin Room',
                'slug' => 'twin-room',
                'description' => '<h2>Two Beds Comfort</h2><p>Our <strong>Twin Room</strong> features two separate beds, perfect for friends or colleagues traveling together.</p><ul><li>Two Single Beds</li><li>City View</li><li>Modern Bathroom</li></ul>',
                'price' => 2800.00,
                'discount_price' => 2600.00,
                'type' => 'Twin',
                'available_rooms' => 6,
                'facilities' => ['Free Wi-Fi', '40" Smart TV', 'AC', 'Room Service', 'Two Beds'],
                'edit_message' => '<p><strong>Perfect for Two:</strong> Ideal for <em>friends</em> or <em>colleagues</em> traveling together!</p>',
                'is_active' => true,
                'order' => 23,
            ],
            [
                'title' => 'Triple Room',
                'slug' => 'triple-room',
                'description' => '<h2>Three Bed Comfort</h2><p>Our <strong>Triple Room</strong> accommodates three guests comfortably with three beds.</p><ul><li>Three Single Beds</li><li>City View</li><li>Modern Bathroom</li></ul>',
                'price' => 3500.00,
                'discount_price' => 3200.00,
                'type' => 'Triple',
                'available_rooms' => 4,
                'facilities' => ['Free Wi-Fi', '43" Smart TV', 'AC', 'Room Service', 'Three Beds'],
                'edit_message' => '<p><strong>Group Friendly:</strong> Perfect for <em>groups of three</em>!</p>',
                'is_active' => true,
                'order' => 24,
            ],
            [
                'title' => 'Quad Room',
                'slug' => 'quad-room',
                'description' => '<h2>Four Bed Accommodation</h2><p>Our <strong>Quad Room</strong> accommodates four guests with four comfortable beds.</p><ul><li>Four Single Beds</li><li>City View</li><li>Modern Bathroom</li></ul>',
                'price' => 4200.00,
                'discount_price' => 3900.00,
                'type' => 'Quad',
                'available_rooms' => 3,
                'facilities' => ['Free Wi-Fi', '43" Smart TV', 'AC', 'Room Service', 'Four Beds'],
                'edit_message' => '<p><strong>Group Special:</strong> Perfect for <em>groups of four</em>!</p>',
                'is_active' => true,
                'order' => 25,
            ],
            [
                'title' => 'Connecting Rooms',
                'slug' => 'connecting-rooms',
                'description' => '<h2>Connected Comfort</h2><p>Our <strong>Connecting Rooms</strong> feature two rooms connected by a door, perfect for families.</p><ul><li>Two Queen Beds</li><li>Connected Rooms</li><li>Two Bathrooms</li></ul>',
                'price' => 7000.00,
                'discount_price' => 6500.00,
                'type' => 'Connecting',
                'available_rooms' => 2,
                'facilities' => ['Free Wi-Fi', 'Two 43" Smart TVs', 'AC', 'Room Service', 'Connected Rooms', 'Two Bathrooms'],
                'edit_message' => '<p><strong>Family Perfect:</strong> <em>Connected rooms</em> perfect for <em>larger families</em>!</p>',
                'is_active' => true,
                'order' => 26,
            ],
            [
                'title' => 'Adjoining Rooms',
                'slug' => 'adjoining-rooms',
                'description' => '<h2>Side by Side</h2><p>Our <strong>Adjoining Rooms</strong> are located next to each other, perfect for groups traveling together.</p><ul><li>Two Queen Beds</li><li>Adjoining Rooms</li><li>Two Bathrooms</li></ul>',
                'price' => 6800.00,
                'discount_price' => 6300.00,
                'type' => 'Adjoining',
                'available_rooms' => 2,
                'facilities' => ['Free Wi-Fi', 'Two 40" Smart TVs', 'AC', 'Room Service', 'Adjoining Rooms', 'Two Bathrooms'],
                'edit_message' => '<p><strong>Group Convenience:</strong> <em>Adjoining rooms</em> for <em>easy access</em>!</p>',
                'is_active' => true,
                'order' => 27,
            ],
            [
                'title' => 'Spa Room',
                'slug' => 'spa-room',
                'description' => '<h2>Spa Experience</h2><p>Our <strong>Spa Room</strong> includes spa amenities and relaxation features for ultimate comfort.</p><ul><li>King Size Bed</li><li>Spa Amenities</li><li>Premium Bathroom</li></ul>',
                'price' => 5800.00,
                'discount_price' => 5300.00,
                'type' => 'Spa',
                'available_rooms' => 2,
                'facilities' => ['Free Wi-Fi', '50" Smart TV', 'AC', 'Mini Bar', 'Room Service', 'Spa Amenities', 'Aromatherapy'],
                'edit_message' => '<p><strong>Spa Package:</strong> Includes <em>spa amenities</em> and <em>aromatherapy</em>!</p>',
                'is_active' => true,
                'order' => 28,
            ],
            [
                'title' => 'Wellness Room',
                'slug' => 'wellness-room',
                'description' => '<h2>Health & Wellness</h2><p>Our <strong>Wellness Room</strong> features fitness equipment and wellness amenities for health-conscious guests.</p><ul><li>Queen Size Bed</li><li>Fitness Equipment</li><li>Modern Bathroom</li></ul>',
                'price' => 4400.00,
                'discount_price' => 4000.00,
                'type' => 'Wellness',
                'available_rooms' => 3,
                'facilities' => ['Free Wi-Fi', '43" Smart TV', 'AC', 'Room Service', 'Fitness Equipment', 'Yoga Mat'],
                'edit_message' => '<p><strong>Wellness Focus:</strong> Includes <em>fitness equipment</em> and <em>wellness amenities</em>!</p>',
                'is_active' => true,
                'order' => 29,
            ],
            [
                'title' => 'Gaming Room',
                'slug' => 'gaming-room',
                'description' => '<h2>Gaming Paradise</h2><p>Our <strong>Gaming Room</strong> features gaming consoles and entertainment systems for gaming enthusiasts.</p><ul><li>Queen Size Bed</li><li>Gaming Console</li><li>Modern Bathroom</li></ul>',
                'price' => 4600.00,
                'discount_price' => 4200.00,
                'type' => 'Gaming',
                'available_rooms' => 2,
                'facilities' => ['Free Wi-Fi', '55" Gaming TV', 'AC', 'Gaming Console', 'Room Service', 'Gaming Setup'],
                'edit_message' => '<p><strong>Gaming Special:</strong> Includes <em>gaming console</em> and <em>gaming setup</em>!</p>',
                'is_active' => true,
                'order' => 30,
            ],
            [
                'title' => 'Music Room',
                'slug' => 'music-room',
                'description' => '<h2>Musical Experience</h2><p>Our <strong>Music Room</strong> features musical instruments and sound systems for music lovers.</p><ul><li>Queen Size Bed</li><li>Musical Instruments</li><li>Sound System</li><li>Modern Bathroom</li></ul>',
                'price' => 4700.00,
                'discount_price' => 4300.00,
                'type' => 'Music',
                'available_rooms' => 2,
                'facilities' => ['Free Wi-Fi', '50" Smart TV', 'AC', 'Musical Instruments', 'Sound System', 'Room Service'],
                'edit_message' => '<p><strong>Music Lovers:</strong> Includes <em>musical instruments</em> and <em>sound system</em>!</p>',
                'is_active' => true,
                'order' => 31,
            ],
            [
                'title' => 'Art Room',
                'slug' => 'art-room',
                'description' => '<h2>Artistic Inspiration</h2><p>Our <strong>Art Room</strong> features artistic decor and creative spaces for art enthusiasts.</p><ul><li>Queen Size Bed</li><li>Artistic Decor</li><li>Creative Space</li><li>Modern Bathroom</li></ul>',
                'price' => 4500.00,
                'discount_price' => 4100.00,
                'type' => 'Art',
                'available_rooms' => 2,
                'facilities' => ['Free Wi-Fi', '43" Smart TV', 'AC', 'Artistic Decor', 'Creative Space', 'Room Service'],
                'edit_message' => '<p><strong>Artistic Retreat:</strong> Perfect for <em>artists</em> and <em>creative minds</em>!</p>',
                'is_active' => true,
                'order' => 32,
            ],
        ];

        // Sample image names (you can replace these with actual image filenames)
        $imageSets = [
            ['main' => 'room-1-main.jpg', 'sub' => ['room-1-sub-1.jpg', 'room-1-sub-2.jpg', 'room-1-sub-3.jpg']],
            ['main' => 'room-2-main.jpg', 'sub' => ['room-2-sub-1.jpg', 'room-2-sub-2.jpg', 'room-2-sub-3.jpg']],
            ['main' => 'room-3-main.jpg', 'sub' => ['room-3-sub-1.jpg', 'room-3-sub-2.jpg', 'room-3-sub-3.jpg']],
            ['main' => 'room-4-main.jpg', 'sub' => ['room-4-sub-1.jpg', 'room-4-sub-2.jpg', 'room-4-sub-3.jpg']],
            ['main' => 'room-5-main.jpg', 'sub' => ['room-5-sub-1.jpg', 'room-5-sub-2.jpg', 'room-5-sub-3.jpg']],
            ['main' => 'room-6-main.jpg', 'sub' => ['room-6-sub-1.jpg', 'room-6-sub-2.jpg', 'room-6-sub-3.jpg']],
            ['main' => 'room-7-main.jpg', 'sub' => ['room-7-sub-1.jpg', 'room-7-sub-2.jpg', 'room-7-sub-3.jpg']],
            ['main' => 'room-8-main.jpg', 'sub' => ['room-8-sub-1.jpg', 'room-8-sub-2.jpg', 'room-8-sub-3.jpg']],
            ['main' => 'room-9-main.jpg', 'sub' => ['room-9-sub-1.jpg', 'room-9-sub-2.jpg', 'room-9-sub-3.jpg']],
            ['main' => 'room-10-main.jpg', 'sub' => ['room-10-sub-1.jpg', 'room-10-sub-2.jpg', 'room-10-sub-3.jpg']],
            ['main' => 'room-11-main.jpg', 'sub' => ['room-11-sub-1.jpg', 'room-11-sub-2.jpg', 'room-11-sub-3.jpg']],
            ['main' => 'room-12-main.jpg', 'sub' => ['room-12-sub-1.jpg', 'room-12-sub-2.jpg', 'room-12-sub-3.jpg']],
            ['main' => 'room-13-main.jpg', 'sub' => ['room-13-sub-1.jpg', 'room-13-sub-2.jpg', 'room-13-sub-3.jpg']],
            ['main' => 'room-14-main.jpg', 'sub' => ['room-14-sub-1.jpg', 'room-14-sub-2.jpg', 'room-14-sub-3.jpg']],
            ['main' => 'room-15-main.jpg', 'sub' => ['room-15-sub-1.jpg', 'room-15-sub-2.jpg', 'room-15-sub-3.jpg']],
            ['main' => 'room-16-main.jpg', 'sub' => ['room-16-sub-1.jpg', 'room-16-sub-2.jpg', 'room-16-sub-3.jpg']],
            ['main' => 'room-17-main.jpg', 'sub' => ['room-17-sub-1.jpg', 'room-17-sub-2.jpg', 'room-17-sub-3.jpg']],
            ['main' => 'room-18-main.jpg', 'sub' => ['room-18-sub-1.jpg', 'room-18-sub-2.jpg', 'room-18-sub-3.jpg']],
            ['main' => 'room-19-main.jpg', 'sub' => ['room-19-sub-1.jpg', 'room-19-sub-2.jpg', 'room-19-sub-3.jpg']],
            ['main' => 'room-20-main.jpg', 'sub' => ['room-20-sub-1.jpg', 'room-20-sub-2.jpg', 'room-20-sub-3.jpg']],
            ['main' => 'room-21-main.jpg', 'sub' => ['room-21-sub-1.jpg', 'room-21-sub-2.jpg', 'room-21-sub-3.jpg']],
            ['main' => 'room-22-main.jpg', 'sub' => ['room-22-sub-1.jpg', 'room-22-sub-2.jpg', 'room-22-sub-3.jpg']],
            ['main' => 'room-23-main.jpg', 'sub' => ['room-23-sub-1.jpg', 'room-23-sub-2.jpg', 'room-23-sub-3.jpg']],
            ['main' => 'room-24-main.jpg', 'sub' => ['room-24-sub-1.jpg', 'room-24-sub-2.jpg', 'room-24-sub-3.jpg']],
            ['main' => 'room-25-main.jpg', 'sub' => ['room-25-sub-1.jpg', 'room-25-sub-2.jpg', 'room-25-sub-3.jpg']],
        ];

        foreach ($rooms as $index => $room) {
            $imageSet = $imageSets[$index] ?? $imageSets[0];
            Room::firstOrCreate(
                ['slug' => $room['slug']],
                array_merge($room, [
                    'main_image' => $imageSet['main'],
                    'sub_images' => $imageSet['sub'],
                ])
            );
        }
    }
}
